master:
  push:
    - name: sync
      runner:
        cpus: 2
      imports: https://cnb.cool/ecustvr/key/-/blob/main/env.yml
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/ECUSTVR/ecustvr.github.io.git
            auth_type: https
            username: ${GITHUB_USERNAME}
            password: ${GITHUB_ACCESS_TOKEN}
        - name: sync to gitee
          image: tencentcom/git-sync
          settings:
            target_url: https://gitee.com/ecustvr/ecustvr.git
            auth_type: https
            username: ${GITEE_USERNAME}
            password: ${GITEE_ACCESS_TOKEN}
    # - name: edgeone
    #   runner:
    #     cpus: 2
    #   imports: https://cnb.cool/ecustvr/key/-/blob/main/env.yml
    #   stages:
    #     # 将构建输出部署到 EdgeOne Pages
    #     - name: Deploy to EdgeOne Pages
    #       image: node:20
    #       script: npx edgeone pages deploy ./ -n ecustvr -t $EDGEONE_API_TOKEN